### ISSUE TITLE
How do I 'register'

### ISSUE THREAD

**Issue by kjell** [cpjfb/MCN2017#4]
Hi - I'd like to attend. The README says 'confirm to get access' but I don't see how. Does opening this issue count?

**Comment by cpjfb** [comment]
Hi Kjell, welcome! Message me on twitter and I'll send you directions

**Comment by cpjfb** [comment]
Or I can email too if you're not on twitter

**Comment by cpjfb** [comment]
would you like to share something you've been working on?

**Comment by kjell** [comment]
(This was all communicated through a different channel - thanks @cpjfb)
